<?php
/**
 * @file
 * Code for the jdrupal_starter feature.
 */

include_once 'jdrupal_starter.features.inc';

function jdrupal_starter_init() {
  
  // Enable CORS
  if(array_key_exists('HTTP_ORIGIN', $_SERVER)) {
    header("Access-Control-Allow-Origin: " . $_SERVER['HTTP_ORIGIN']);
    header("Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE");
    header("Access-Control-Allow-Headers: content-type, X-CSRF-Token, X-CSRFToken");
    header("Access-Control-Allow-Credentials: true");
  }

}


